In [1]:
import pandas as pd
import os
from datetime import datetime

In [2]:
SUPPORTED_STOCKS = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "AMZN",
    "NVDA"
]

RESULTS_DIR = "../results"
REPORTS_DIR = "../reports"

os.makedirs(RESULTS_DIR, exist_ok=True)

all_ai_recommendations = []

In [3]:
for ticker in SUPPORTED_STOCKS:

    print("=" * 70)
    print(f"Processing {ticker}")
    print("=" * 70)

    # -----------------------------
    # Load datasets
    # -----------------------------

    signals = pd.read_csv(
        f"{RESULTS_DIR}/{ticker}_recommendation.csv"
    )

    sentiment = pd.read_csv(
        f"{REPORTS_DIR}/{ticker}/news_sentiment.csv"
    )

    forecast = pd.read_csv(
        f"{REPORTS_DIR}/{ticker}/prophet_forecast.csv"
    )

    print("Recommendation")
    display(signals)

    print("Sentiment Sample")
    display(sentiment.head())

    print("Forecast Sample")
    display(forecast.head())


    # -----------------------------
    # Extract values
    # -----------------------------

    recommendation = signals.loc[0, "Recommendation"]

    confidence = signals.loc[0, "Confidence (%)"]

    current_price = signals.loc[0, "Current Price"]

    predicted_price = signals.loc[0, "Predicted Price"]

    trading_score = signals.loc[0, "Trading Score"]

    sentiment_score = signals.loc[0, "Average Sentiment"]


    # -----------------------------
    # Generate AI Insights
    # -----------------------------

    insights = []

    if predicted_price > current_price:

        insights.append(
            "AI predicts a potential upward movement in stock price."
        )

    else:

        insights.append(
            "AI predicts a possible downward movement in stock price."
        )


    if recommendation == "BUY":

        insights.append(
            "Technical indicators suggest a BUY opportunity."
        )

    elif recommendation == "SELL":

        insights.append(
            "Technical indicators suggest a SELL opportunity."
        )

    else:

        insights.append(
            "Current market conditions suggest HOLD."
        )


    if sentiment_score > 0:

        insights.append(
            "Positive news sentiment may support price growth."
        )

    elif sentiment_score < 0:

        insights.append(
            "Negative news sentiment may affect short-term performance."
        )

    else:

        insights.append(
            "Neutral news sentiment observed."
        )


    if trading_score >= 70:

        insights.append(
            "High confidence trading opportunity."
        )

    elif trading_score >= 50:

        insights.append(
            "Moderate confidence trading opportunity."
        )

    else:

        insights.append(
            "Low confidence. Trade carefully."
        )


    insights.append(
        f"Overall Recommendation: {recommendation} ({confidence:.2f}% Confidence)"
    )


    print("\nGenerated Insights\n")

    for i, text in enumerate(insights, start=1):

        print(f"{i}. {text}")


    recommendation_df = pd.DataFrame({

        "Ticker":[ticker],

        "Generated On":[datetime.now()],

        "Recommendation":[recommendation],

        "Confidence (%)":[confidence],

        "Trading Score":[trading_score],

        "Average Sentiment":[sentiment_score],

        "Insights":[" | ".join(insights)]

    })


    recommendation_df.to_csv(

        f"{RESULTS_DIR}/{ticker}_ai_recommendation.csv",

        index=False

    )

    all_ai_recommendations.append(recommendation_df)

======================================================================
Processing AAPL
======================================================================
Recommendation

,Ticker,Current Price,Predicted Price,Average Sentiment,Trading Score,Recommendation,Confidence (%),Generated On
0,AAPL,340.08,302.69,0.132,-2,SELL,40,2026-07-29 20:34:35.131345

Sentiment Sample

,Ticker,Company,Date,Title,Description,Source,Text,Polarity,Sentiment
0,AAPL,Apple,2026-07-28T14:55:40Z,Apple’s reported ‘HomePad’ may launch as early...,"For years, we’ve heard rumors of a new home hu...",Biztoc.com,Apple’s reported ‘HomePad’ may launch as early...,0.146753,Positive
1,AAPL,Apple,2026-07-28T14:55:08Z,Banks Want Technophobes and Late Adopters to U...,Paze faces an uphill battle to get people to u...,Biztoc.com,Banks Want Technophobes and Late Adopters to U...,0.044444,Positive
2,AAPL,Apple,2026-07-28T14:53:31Z,5 Reasons to Buy a MacBook Air Now Instead of ...,Apple's next MacBook Air is several months awa...,MacRumors,5 Reasons to Buy a MacBook Air Now Instead of ...,0.283333,Positive
3,AAPL,Apple,2026-07-28T14:53:14Z,S&P 500 futures steady as chip stocks take a t...,The chip sector's downturn could signal broade...,Crypto Briefing,S&P 500 futures steady as chip stocks take a t...,0.194444,Positive
4,AAPL,Apple,2026-07-28T14:52:27Z,Coleen Rooney shows off her gym-honed figure i...,She is known for her love of working out.,Dailymail.com,Coleen Rooney shows off her gym-honed figure i...,0.160714,Positive

Forecast Sample

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2023-03-15,157.885360,155.270550,169.983885,157.885360,157.885360,4.903343,4.903343,4.903343,1.022900,1.022900,1.022900,3.880443,3.880443,3.880443,0.0,0.0,0.0,162.788703
1,2023-03-16,158.303511,155.130378,170.559933,158.303511,158.303511,4.287665,4.287665,4.287665,1.029116,1.029116,1.029116,3.258549,3.258549,3.258549,0.0,0.0,0.0,162.591176
2,2023-03-17,158.721662,155.235935,170.436304,158.721662,158.721662,3.944833,3.944833,3.944833,1.249535,1.249535,1.249535,2.695299,2.695299,2.695299,0.0,0.0,0.0,162.666496
3,2023-03-20,159.976116,155.127855,169.736781,159.976116,159.976116,2.501773,2.501773,2.501773,1.193795,1.193795,1.193795,1.307978,1.307978,1.307978,0.0,0.0,0.0,162.477889
4,2023-03-21,160.394267,155.532756,169.465246,160.394267,160.394267,2.116530,2.116530,2.116530,1.192585,1.192585,1.192585,0.923945,0.923945,0.923945,0.0,0.0,0.0,162.510797

Generated Insights

1. AI predicts a possible downward movement in stock price.
2. Technical indicators suggest a SELL opportunity.
3. Positive news sentiment may support price growth.
4. Low confidence. Trade carefully.
5. Overall Recommendation: SELL (40.00% Confidence)
======================================================================
Processing MSFT
======================================================================
Recommendation

,Ticker,Current Price,Predicted Price,Average Sentiment,Trading Score,Recommendation,Confidence (%),Generated On
0,MSFT,393.35,520.93,0.114,2,HOLD,40,2026-07-29 20:34:35.678137

Sentiment Sample

,Ticker,Company,Date,Title,Description,Source,Text,Polarity,Sentiment
0,MSFT,Microsoft,2026-07-28T14:57:31Z,The OpenAI Hack Is Fueling a New Fight Over Op...,The industry's response to the OpenAI incident...,Time,The OpenAI Hack Is Fueling a New Fight Over Op...,0.068182,Positive
1,MSFT,Microsoft,2026-07-28T14:56:22Z,OpenAI CEO Sam Altman says AI has entered the ...,OpenAI CEO Sam Altman recently declared on the...,Tom's Hardware UK,OpenAI CEO Sam Altman says AI has entered the ...,-0.300000,Negative
2,MSFT,Microsoft,2026-07-28T14:53:14Z,S&P 500 futures steady as chip stocks take a t...,The chip sector's downturn could signal broade...,Crypto Briefing,S&P 500 futures steady as chip stocks take a t...,0.194444,Positive
3,MSFT,Microsoft,2026-07-28T14:53:00Z,The best AI governance tools and platforms in ...,AI governance has become a boardroom priority....,Techtarget.com,The best AI governance tools and platforms in ...,1.000000,Positive
4,MSFT,Microsoft,2026-07-28T14:52:56Z,"Virginia Data Centers, Data Center E-Waste, Av...",AI PROBLEMS Politico: Emails show how Virginia...,Researchbuzz.me,"Virginia Data Centers, Data Center E-Waste, Av...",0.088889,Positive

Forecast Sample

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2023-03-15,317.113442,272.396726,297.604465,317.113442,317.113442,-31.295586,-31.295586,-31.295586,10.654020,10.654020,10.654020,-41.949606,-41.949606,-41.949606,0.0,0.0,0.0,285.817857
1,2023-03-16,316.942693,272.755408,298.181846,316.942693,316.942693,-31.615842,-31.615842,-31.615842,10.513626,10.513626,10.513626,-42.129468,-42.129468,-42.129468,0.0,0.0,0.0,285.326851
2,2023-03-17,316.771944,273.713751,299.292204,316.771944,316.771944,-31.126915,-31.126915,-31.126915,11.096093,11.096093,11.096093,-42.223007,-42.223007,-42.223007,0.0,0.0,0.0,285.645029
3,2023-03-20,316.259696,272.495899,296.928181,316.259696,316.259696,-31.425159,-31.425159,-31.425159,10.605586,10.605586,10.605586,-42.030744,-42.030744,-42.030744,0.0,0.0,0.0,284.834537
4,2023-03-21,316.088947,272.234581,297.035110,316.088947,316.088947,-31.277082,-31.277082,-31.277082,10.556009,10.556009,10.556009,-41.833091,-41.833091,-41.833091,0.0,0.0,0.0,284.811865

Generated Insights

1. AI predicts a potential upward movement in stock price.
2. Current market conditions suggest HOLD.
3. Positive news sentiment may support price growth.
4. Low confidence. Trade carefully.
5. Overall Recommendation: HOLD (40.00% Confidence)
======================================================================
Processing GOOGL
======================================================================
Recommendation

,Ticker,Current Price,Predicted Price,Average Sentiment,Trading Score,Recommendation,Confidence (%),Generated On
0,GOOGL,333.71,333.44,0.143,-4,SELL,80,2026-07-29 20:34:36.043325

Sentiment Sample

,Ticker,Company,Date,Title,Description,Source,Text,Polarity,Sentiment
0,GOOGL,Google,2026-07-28T14:57:31Z,The OpenAI Hack Is Fueling a New Fight Over Op...,The industry's response to the OpenAI incident...,Time,The OpenAI Hack Is Fueling a New Fight Over Op...,0.068182,Positive
1,GOOGL,Google,2026-07-28T14:56:22Z,OpenAI CEO Sam Altman says AI has entered the ...,OpenAI CEO Sam Altman recently declared on the...,Tom's Hardware UK,OpenAI CEO Sam Altman says AI has entered the ...,-0.300000,Negative
2,GOOGL,Google,2026-07-28T14:55:41Z,Cellphone users report outages across major ca...,Customers for several major cell service carri...,Biztoc.com,Cellphone users report outages across major ca...,0.041667,Positive
3,GOOGL,Google,2026-07-28T14:55:40Z,Apple’s reported ‘HomePad’ may launch as early...,"For years, we’ve heard rumors of a new home hu...",Biztoc.com,Apple’s reported ‘HomePad’ may launch as early...,0.146753,Positive
4,GOOGL,Google,2026-07-28T14:55:19Z,Claude chats showed up in Google Search. Here’...,"It’s one thing for ChatGPT, Claude, or Gemini ...",PCWorld,Claude chats showed up in Google Search. Here’...,0.000000,Neutral

Forecast Sample

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2023-03-15,99.099561,94.159981,107.119009,99.099561,99.099561,1.454788,1.454788,1.454788,0.785374,0.785374,0.785374,0.669415,0.669415,0.669415,0.0,0.0,0.0,100.554350
1,2023-03-16,99.423292,94.833642,107.111995,99.423292,99.423292,1.120102,1.120102,1.120102,0.543569,0.543569,0.543569,0.576534,0.576534,0.576534,0.0,0.0,0.0,100.543394
2,2023-03-17,99.747022,94.590407,107.587551,99.747022,99.747022,1.266497,1.266497,1.266497,0.778215,0.778215,0.778215,0.488282,0.488282,0.488282,0.0,0.0,0.0,101.013519
3,2023-03-20,100.718213,95.588616,107.996380,100.718213,100.718213,1.070069,1.070069,1.070069,0.843043,0.843043,0.843043,0.227026,0.227026,0.227026,0.0,0.0,0.0,101.788282
4,2023-03-21,101.041943,95.647677,108.347383,101.041943,101.041943,0.913282,0.913282,0.913282,0.779161,0.779161,0.779161,0.134121,0.134121,0.134121,0.0,0.0,0.0,101.955225

Generated Insights

1. AI predicts a possible downward movement in stock price.
2. Technical indicators suggest a SELL opportunity.
3. Positive news sentiment may support price growth.
4. Low confidence. Trade carefully.
5. Overall Recommendation: SELL (80.00% Confidence)
======================================================================
Processing AMZN
======================================================================
Recommendation

,Ticker,Current Price,Predicted Price,Average Sentiment,Trading Score,Recommendation,Confidence (%),Generated On
0,AMZN,230.86,246.3,0.152,0,HOLD,0,2026-07-29 20:34:36.255701

Sentiment Sample

,Ticker,Company,Date,Title,Description,Source,Text,Polarity,Sentiment
0,AMZN,Amazon,2026-07-28T14:57:45Z,Add the LEGO Star Wars SMART Play Mos Eisley C...,We just spotted a deal at Amazon that cuts the...,9to5Toys,Add the LEGO Star Wars SMART Play Mos Eisley C...,0.159276,Positive
1,AMZN,Amazon,2026-07-28T14:57:31Z,The OpenAI Hack Is Fueling a New Fight Over Op...,The industry's response to the OpenAI incident...,Time,The OpenAI Hack Is Fueling a New Fight Over Op...,0.068182,Positive
2,AMZN,Amazon,2026-07-28T14:53:31Z,5 Reasons to Buy a MacBook Air Now Instead of ...,Apple's next MacBook Air is several months awa...,MacRumors,5 Reasons to Buy a MacBook Air Now Instead of ...,0.283333,Positive
3,AMZN,Amazon,2026-07-28T14:53:14Z,S&P 500 futures steady as chip stocks take a t...,The chip sector's downturn could signal broade...,Crypto Briefing,S&P 500 futures steady as chip stocks take a t...,0.194444,Positive
4,AMZN,Amazon,2026-07-28T14:52:28Z,Hundreds of Ukrainian Drones Target Moscow in ...,Hundreds of Ukrainian Drones Target Moscow in ...,Slashdot.org,Hundreds of Ukrainian Drones Target Moscow in ...,0.175000,Positive

Forecast Sample

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2023-03-15,106.627308,93.865348,107.154333,106.627308,106.627308,-5.963718,-5.963718,-5.963718,2.191009,2.191009,2.191009,-8.154727,-8.154727,-8.154727,0.0,0.0,0.0,100.663589
1,2023-03-16,106.761161,93.881120,106.677244,106.761161,106.761161,-6.280443,-6.280443,-6.280443,2.028306,2.028306,2.028306,-8.308748,-8.308748,-8.308748,0.0,0.0,0.0,100.480718
2,2023-03-17,106.895014,93.647594,107.557745,106.895014,106.895014,-5.998878,-5.998878,-5.998878,2.418095,2.418095,2.418095,-8.416973,-8.416973,-8.416973,0.0,0.0,0.0,100.896136
3,2023-03-20,107.296574,94.411860,108.143167,107.296574,107.296574,-6.179014,-6.179014,-6.179014,2.329589,2.329589,2.329589,-8.508602,-8.508602,-8.508602,0.0,0.0,0.0,101.117560
4,2023-03-21,107.430427,94.314418,108.089516,107.430427,107.430427,-6.264829,-6.264829,-6.264829,2.214644,2.214644,2.214644,-8.479473,-8.479473,-8.479473,0.0,0.0,0.0,101.165599

Generated Insights

1. AI predicts a potential upward movement in stock price.
2. Current market conditions suggest HOLD.
3. Positive news sentiment may support price growth.
4. Low confidence. Trade carefully.
5. Overall Recommendation: HOLD (0.00% Confidence)
======================================================================
Processing NVDA
======================================================================
Recommendation

,Ticker,Current Price,Predicted Price,Average Sentiment,Trading Score,Recommendation,Confidence (%),Generated On
0,NVDA,197.01,203.17,0.122,0,HOLD,0,2026-07-29 20:34:36.461338

Sentiment Sample

,Ticker,Company,Date,Title,Description,Source,Text,Polarity,Sentiment
0,NVDA,NVIDIA,2026-07-28T14:58:00Z,"Ace Combat 8 requires ray tracing GPU, 32GB RA...",The minimum processor requirement for playing ...,TechSpot,"Ace Combat 8 requires ray tracing GPU, 32GB RA...",0.050000,Positive
1,NVDA,NVIDIA,2026-07-28T14:57:31Z,The OpenAI Hack Is Fueling a New Fight Over Op...,The industry's response to the OpenAI incident...,Time,The OpenAI Hack Is Fueling a New Fight Over Op...,0.068182,Positive
2,NVDA,NVIDIA,2026-07-28T14:55:42Z,"Micron, Nvidia fall after SK Hynix plunges nea...",Semiconductor stocks fell on Tuesday following...,Biztoc.com,"Micron, Nvidia fall after SK Hynix plunges nea...",0.025000,Positive
3,NVDA,NVIDIA,2026-07-28T14:55:04Z,Nvidia says smuggling is a 'nonstarter' as Tai...,A senior sales manager allegedly helped route ...,Digitimes,Nvidia says smuggling is a 'nonstarter' as Tai...,-0.100000,Negative
4,NVDA,NVIDIA,2026-07-28T14:53:15Z,A New AI Shortage Is Coming. One CEO Just Pred...,Lumentum's CEO just named the obscure semicond...,24/7 Wall St.,A New AI Shortage Is Coming. One CEO Just Pred...,0.068182,Positive

Forecast Sample

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2023-03-15,36.683913,23.078875,37.950844,36.683913,36.683913,-6.273266,-6.273266,-6.273266,2.589477,2.589477,2.589477,-8.862743,-8.862743,-8.862743,0.0,0.0,0.0,30.410647
1,2023-03-16,36.652824,22.800779,38.022718,36.652824,36.652824,-6.229747,-6.229747,-6.229747,2.715288,2.715288,2.715288,-8.945035,-8.945035,-8.945035,0.0,0.0,0.0,30.423077
2,2023-03-17,36.621735,22.724734,37.617075,36.621735,36.621735,-6.367846,-6.367846,-6.367846,2.623775,2.623775,2.623775,-8.991621,-8.991621,-8.991621,0.0,0.0,0.0,30.253888
3,2023-03-20,36.528466,22.187622,37.514334,36.528466,36.528466,-6.561025,-6.561025,-6.561025,2.421017,2.421017,2.421017,-8.982042,-8.982042,-8.982042,0.0,0.0,0.0,29.967441
4,2023-03-21,36.497377,22.896726,37.083430,36.497377,36.497377,-6.568291,-6.568291,-6.568291,2.386070,2.386070,2.386070,-8.954361,-8.954361,-8.954361,0.0,0.0,0.0,29.929086

Generated Insights

1. AI predicts a potential upward movement in stock price.
2. Current market conditions suggest HOLD.
3. Positive news sentiment may support price growth.
4. Low confidence. Trade carefully.
5. Overall Recommendation: HOLD (0.00% Confidence)

In [4]:
final_df = pd.concat(
    all_ai_recommendations,
    ignore_index=True
)

final_df.to_csv(
    f"{RESULTS_DIR}/all_ai_recommendations.csv",
    index=False
)

print("=" * 70)
print("LAB 11 COMPLETED SUCCESSFULLY")
print("=" * 70)

display(final_df)

print("\nGenerated Files\n")

for ticker in SUPPORTED_STOCKS:

    print(f"{ticker}_ai_recommendation.csv")

print("\nCombined File")

print("all_ai_recommendations.csv")

======================================================================
LAB 11 COMPLETED SUCCESSFULLY
======================================================================

,Ticker,Generated On,Recommendation,Confidence (%),Trading Score,Average Sentiment,Insights
0,AAPL,2026-07-29 21:27:15.018647,SELL,40,-2,0.132,AI predicts a possible downward movement in st...
1,MSFT,2026-07-29 21:27:15.244878,HOLD,40,2,0.114,AI predicts a potential upward movement in sto...
2,GOOGL,2026-07-29 21:27:15.455863,SELL,80,-4,0.143,AI predicts a possible downward movement in st...
3,AMZN,2026-07-29 21:27:15.819098,HOLD,0,0,0.152,AI predicts a potential upward movement in sto...
4,NVDA,2026-07-29 21:27:16.158973,HOLD,0,0,0.122,AI predicts a potential upward movement in sto...

Generated Files

AAPL_ai_recommendation.csv
MSFT_ai_recommendation.csv
GOOGL_ai_recommendation.csv
AMZN_ai_recommendation.csv
NVDA_ai_recommendation.csv

Combined File
all_ai_recommendations.csv